FROM python:3.9-alpine
WORKDIR /code
ADD . /code
ENV DOCKER_IN_USE=yes
RUN apk add build-base
RUN pip install -r requirements.txt
CMD ["celery", "-A", "monolith.background", "worker", "-l", "INFO", "-B"]