FROM python:3.9-alpine
ADD . /code
WORKDIR /code
RUN apk add build-base py-pip jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib
RUN pip3 install -r requirements.txt
RUN python3 -m spacy download en
CMD ["sh", "start.sh"]