FROM python:3.9
WORKDIR /code
ADD . /code
ENV TZ=Europe/Rome
ENV DOCKER_IN_USE=yes
ENV LIBRARY_PATH=/lib:/usr/lib
RUN pip3 install -r requirements.txt
RUN python3 -m spacy download en
CMD ["celery", "-A", "monolith.background", "worker", "-l", "INFO", "-B"]