version: 2
 
jobs:
 
  toxify:
 
      docker:
        - image: circleci/python:3.9
 
      steps:
 
        - checkout
 
        - run: pip install tox

        - run: tox -e py39
 
 
workflows:
  version: 2
 
  monolith_project:
    jobs:
      - toxify